# Generated by Django 4.2.30 on 2026-05-07 02:21

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_tenant_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enable_delivery_photo",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, drivers must upload a photo to mark an order as delivered.",
                    ),
                ),
                (
                    "require_signature",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, drivers must collect a signature on delivery.",
                    ),
                ),
                (
                    "auto_assign_orders",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic order assignment to available drivers.",
                    ),
                ),
                (
                    "max_cancellation_time",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Maximum time (in minutes) after which an order cannot be cancelled by the customer.",
                    ),
                ),
                ("support_contact_number", models.CharField(blank=True, max_length=20)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("company_name", models.CharField(blank=True, max_length=100)),
                (
                    "theme_color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex code for the primary theme color.",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Configuration",
                "verbose_name_plural": "Admin Configuration",
            },
        ),
        migrations.CreateModel(
            name="AdminUserProxy",
            fields=[],
            options={
                "verbose_name": "User Management",
                "verbose_name_plural": "User Management",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
