# Generated by Django 5.2.11 on 2026-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminconfiguration",
            name="bottle_penalty_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Default penalty charge per lost or broken bottle.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="adminconfiguration",
            name="charge_bottle_penalty",
            field=models.BooleanField(
                default=False,
                help_text="Enable penalty charges for lost or broken empty bottles.",
            ),
        ),
    ]
