# Generated by Django 4.2.30 on 2026-06-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_adminconfiguration_bottle_penalty_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfiguration',
            name='company_upi_id',
            field=models.CharField(blank=True, help_text='Company UPI VPA (e.g., company@okaxis)', max_length=100),
        ),
        migrations.AddField(
            model_name='adminconfiguration',
            name='company_upi_name',
            field=models.CharField(blank=True, help_text='Company Display Name for UPI (e.g., Pench Foods)', max_length=100),
        ),
    ]
