# Generated by Django 5.2.15 on 2026-08-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_adminconfiguration_company_upi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfiguration',
            name='is_secured',
            field=models.BooleanField(default=False, help_text='Default secured route flag for tenant routes.'),
        ),
    ]
