# Generated by Django 4.2.30 on 2026-05-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_scheduled_delivery_date_order_subscription'),
        ('taxation', '0002_alter_producttaxcategory_options_and_more'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgatewaylog',
            name='transaction',
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='auto_recharge_amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='auto_recharge_enabled',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='auto_recharge_threshold',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='balance_after',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Balance after this transaction', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit (Add Funds)'), ('debit', 'Debit (Payment)'), ('refund', 'Refund')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='PaymentGatewayLog',
        ),
    ]
