# Generated by Django 6.0.4 on 2026-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='require_pod',
            field=models.BooleanField(default=False, help_text='If enabled, drivers must upload a photo to mark an order as delivered.'),
        ),
    ]
