# Generated by Django 6.0.4 on 2026-05-15 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_city_require_pod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidaycalendar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='holidaycalendar',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.city'),
        ),
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='tenants.city'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaycalendar',
            unique_together={('city', 'date')},
        ),
    ]
