# Generated by Django 6.0.4 on 2026-05-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_holidaycalendar_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
