# Generated by Django 6.0.4 on 2026-05-15 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_delete_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Geofencing boundary for this city.', null=True, srid=4326),
        ),
    ]
