# Generated by Django 6.0.4 on 2026-05-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_company_city_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(help_text='Unique city code, e.g. MUM, DEL.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('company', 'code')},
        ),
    ]
