# Generated by Django 4.2.30 on 2026-06-18 11:20

from django.db import migrations, models


def convert_empty_emails_to_none(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
    ]

    operations = [
        # 1. Make email nullable first
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        # 2. Convert empty strings to None/NULL
        migrations.RunPython(convert_empty_emails_to_none, reverse_code=migrations.RunPython.noop),
        # 3. Apply the uniqueness constraint
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
