# Generated by Django 5.2.15 on 2026-08-11 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of when the user's password was last changed.", null=True),
        ),
        migrations.CreateModel(
            name='LoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_or_phone', models.CharField(max_length=150)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED_INVALID_PASSWORD', 'Failed - Invalid Password'), ('FAILED_USER_NOT_FOUND', 'Failed - User Not Found'), ('FAILED_INACTIVE', 'Failed - User Inactive')], max_length=40)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Audit Log',
                'verbose_name_plural': 'Login Audit Logs',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='set_password', help_text='Where the password was changed from (e.g. self_reset, admin_update, driver_credentials_update).', max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who initiated/executed the password change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords_changed_by_me', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Change Log',
                'verbose_name_plural': 'Password Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
