# Generated by Django 5.2.15 on 2026-08-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_password_changed_at_loginauditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED_INVALID_PASSWORD', 'Failed - Invalid Password'), ('FAILED_USER_NOT_FOUND', 'Failed - User Not Found'), ('FAILED_INACTIVE', 'Failed - User Inactive'), ('TOKEN_REFRESH_SUCCESS', 'Token Refresh Success'), ('TOKEN_REFRESH_FAILED', 'Token Refresh Failed')], max_length=40),
        ),
    ]
