# Generated by Django 4.2.30 on 2026-05-05 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottletransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='bottletransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bottleinventory',
            name='bottle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.bottletype'),
        ),
        migrations.AddField(
            model_name='bottleinventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_inventory', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='bottleinventory',
            unique_together={('bottle_type', 'warehouse')},
        ),
    ]
