# Generated by Django 4.2.30 on 2026-05-05 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBottleBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='adjusted_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='stock',
        ),
        migrations.AlterModelOptions(
            name='bottletype',
            options={},
        ),
        migrations.RemoveField(
            model_name='bottletransaction',
            name='qr_codes',
        ),
        migrations.DeleteModel(
            name='BottleInventory',
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
        migrations.AddField(
            model_name='customerbottlebalance',
            name='bottle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bottletype'),
        ),
        migrations.AddField(
            model_name='customerbottlebalance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_balances', to='crm.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='customerbottlebalance',
            unique_together={('customer', 'bottle_type')},
        ),
    ]
