# Generated by Django 4.2.30 on 2026-05-20 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_zone'),
        ('inventory', '0003_customerbottlebalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='crm.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Customer Product Price',
                'verbose_name_plural': 'Customer Product Prices',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
