# Generated by Django 4.2.30 on 2026-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_customerproductprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductprice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
