# Generated by Django 5.2.11 on 2026-05-23 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_warehouse_latitude_warehouse_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAvailability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "product"],
                "unique_together": {("product", "date")},
            },
        ),
    ]
