# Generated by Django 5.2.11 on 2026-05-24 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_productavailability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound / Supplier"),
                            ("outbound", "Outbound / Order Dispatch"),
                            ("adjustment", "Manual Adjustment"),
                            ("transfer", "Warehouse Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for inbound/adjustments, negative for outbound/transfers"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Order ID, Supplier Invoice, or Transfer ID",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
