# Generated by Django 4.2.30 on 2026-05-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottletransaction',
            name='bottle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.bottletype'),
        ),
    ]
