# Generated by Django 5.2.11 on 2026-05-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="raw_material",
            field=models.ForeignKey(
                blank=True,
                help_text="The base raw bulk ingredient/product (e.g. Raw Bulk Milk) used to fill this package.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packaged_variants",
                to="inventory.product",
            ),
        ),
    ]
