# Generated by Django 5.2.11 on 2026-05-24 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_product_raw_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(default="Litre", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="product",
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stock",
            name="raw_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_levels",
                to="inventory.rawmaterial",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="raw_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="inventory.rawmaterial",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="raw_material",
            field=models.ForeignKey(
                blank=True,
                help_text="The base raw material ingredient used to fill this package.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.rawmaterial",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("raw_material", "warehouse")},
        ),
        migrations.RemoveField(
            model_name="stock",
            name="product",
        ),
    ]
