# Generated by Django 4.2.30 on 2026-05-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_bottletransaction_bottle_type'),
        ('inventory', '0010_rawmaterial_remove_stockmovement_product_and_more'),
    ]

    operations = [
    ]
