# Generated by Django 4.2.30 on 2026-06-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_merge_20260527_1248'),
        ('inventory', '0011_merge_20260528_0751'),
    ]

    operations = [
    ]
