# Generated by Django 5.2.15 on 2026-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_merge_20260602_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbottlebalance',
            name='broken_balance',
            field=models.IntegerField(default=0),
        ),
    ]
