# Generated by Django 5.2.15 on 2026-07-29 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_customer_crm_custome_name_0c497a_idx_and_more'),
        ('inventory', '0013_customerbottlebalance_broken_balance'),
        ('orders', '0015_route_stoppage_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bottletransaction',
            index=models.Index(fields=['customer'], name='inventory_b_custome_a072e3_idx'),
        ),
        migrations.AddIndex(
            model_name='bottletransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_b_transac_416e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='bottletransaction',
            index=models.Index(fields=['created_at'], name='inventory_b_created_1679ff_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbottlebalance',
            index=models.Index(fields=['customer'], name='inventory_c_custome_0c6bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbottlebalance',
            index=models.Index(fields=['bottle_type'], name='inventory_c_bottle__6ea995_idx'),
        ),
    ]
