from unittest.mock import patch, MagicMock
from django.test import TestCase
from django_tenants.test.cases import TenantTestCase


class TestTSPSolver(TestCase):
    """Unit tests for the OR-Tools TSP solver."""

    def test_solve_returns_valid_route(self):
        """Solver returns a route starting and ending at depot (index 0)."""
        from routing.services.tsp_solver import solve_tsp

        matrix = [
            [0, 10, 15, 20],
            [10, 0, 35, 25],
            [15, 35, 0, 30],
            [20, 25, 30, 0],
        ]
        with patch("routing.services.tsp_solver.TIME_LIMIT", 2):
            result = solve_tsp(matrix)

        self.assertIsNotNone(result)
        self.assertEqual(result[0], 0, "Route must start at depot")
        self.assertEqual(result[-1], 0, "Route must return to depot")
        self.assertEqual(len(result), 5, "Must visit all 4 nodes + return")

    def test_solve_too_few_stops(self):
        from routing.services.tsp_solver import solve_tsp

        result = solve_tsp([[0]])
        self.assertIsNone(result)


class TestOSRMFallback(TestCase):
    """OSRM client falls back to Euclidean when the API is unavailable."""

    @patch("routing.services.osrm_client.requests.get")
    def test_fallback_on_network_error(self, mock_get):
        from routing.services.osrm_client import build_distance_matrix
        import requests as req_lib

        mock_get.side_effect = req_lib.RequestException("Connection refused")

        stops = [
            {"lat": 19.076, "lon": 72.877},
            {"lat": 19.080, "lon": 72.880},
            {"lat": 19.070, "lon": 72.870},
        ]
        matrix = build_distance_matrix(stops)
        self.assertEqual(len(matrix), 3)
        self.assertEqual(len(matrix[0]), 3)
        self.assertEqual(matrix[0][0], 0.0)

    def test_raises_for_single_stop(self):
        from routing.services.osrm_client import build_distance_matrix

        with self.assertRaises(ValueError):
            build_distance_matrix([{"lat": 19.0, "lon": 72.0}])


class TestDeductStock(TenantTestCase):
    """Inventory service: deduct_stock_on_delivery tests."""

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = "Test City"
        tenant.state = "Test State"
        tenant.code = "TST"
        tenant.create_schema(sync_schema=True)

    def test_deduct_stock_creates_record_when_missing(self):
        from inventory.services import deduct_stock_on_delivery
        from inventory.models import Warehouse, Stock, RawMaterial, Product, BottleType, StockMovement, StockMovementType
        from orders.models import Order, OrderItem
        from crm.models import Customer
        import datetime
        
        # Create warehouse, raw material, product, and order
        warehouse = Warehouse.objects.create(name="Test Warehouse", is_active=True)
        raw_mat = RawMaterial.objects.create(name="Milk Raw", unit="litre")
        bottle = BottleType.objects.create(name="1L Bottle", volume_ml=1000)
        product = Product.objects.create(
            name="Milk Product", sku="MPROD", unit_price=10.0,
            raw_material=raw_mat, bottle_type=bottle, is_returnable=True
        )
        
        customer = Customer.objects.create(name="Cust", email="cust@example.com")
        order = Order.objects.create(
            customer=customer, scheduled_delivery_date=datetime.date.today(),
            delivery_address="Add"
        )
        OrderItem.objects.create(order=order, product=product, quantity=5, unit_price=product.unit_price)
        
        # Call deduct_stock_on_delivery
        deduct_stock_on_delivery(order)
        
        # Check stock was created and is negative (0 - 5 = -5)
        stock = Stock.objects.get(raw_material=raw_mat, warehouse=warehouse)
        self.assertEqual(stock.quantity, -5)
        
        # Verify StockMovement was created
        movement = StockMovement.objects.get(raw_material=raw_mat, warehouse=warehouse)
        self.assertEqual(movement.quantity, -5)
        self.assertEqual(movement.movement_type, StockMovementType.OUTBOUND)



class TestAutoGenerateDailyRoutes(TenantTestCase):
    """Unit tests for auto_generate_daily_routes Celery task."""

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = "Test City"
        tenant.state = "Test State"
        tenant.code = "TST"
        tenant.create_schema(sync_schema=True)

    def setUp(self):
        super().setUp()
        from django.contrib.auth import get_user_model
        from routing.models import Zone
        from crm.models import Customer
        from orders.models import Order, OrderStatus
        from django.conf import settings
        import datetime

        User = get_user_model()
        self.driver_user = User.objects.create_user(
            username="test_driver",
            email="driver@example.com",
            password="testpassword",
            is_driver=True,
        )
        self.zone = Zone.objects.create(
            name="Test Zone", assigned_driver=self.driver_user
        )

        HAS_GIS = getattr(settings, "HAS_GDAL", False)
        if HAS_GIS:
            from django.contrib.gis.geos import Point

            loc = Point(79.0, 21.0)
        else:
            loc = {"longitude": 79.0, "latitude": 21.0}

        self.customer = Customer.objects.create(
            name="Test Customer",
            email="customer@example.com",
            zone=self.zone,
            location=loc,
            is_new=False,
        )
        # Create a pending order for today
        self.order = Order.objects.create(
            customer=self.customer,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=100.00,
        )

    def test_auto_generate_daily_routes_creates_route(self):
        from routing.tasks import auto_generate_daily_routes
        from orders.models import Route, RouteStop
        import datetime

        # Run task
        results = auto_generate_daily_routes()

        # Check results
        self.assertIn("test", results)
        stats = results["test"]
        self.assertEqual(stats["status"], "success")
        self.assertEqual(stats["created_routes"], 1)
        self.assertEqual(stats["skipped_zones"], 0)

        # Verify Route was created in database
        route = Route.objects.filter(
            driver=self.driver_user, delivery_date=datetime.date.today()
        ).first()
        self.assertIsNotNone(route)
        self.assertEqual(
            route.name, f"Test Zone - {datetime.date.today().strftime('%Y-%m-%d')}"
        )

        # Verify RouteStop was created
        stop = RouteStop.objects.filter(route=route).first()
        self.assertIsNotNone(stop)
        self.assertEqual(stop.order, self.order)


class TestSubmitUndelivered(TenantTestCase):
    """Unit tests for submit_undelivered and mark_undelivered endpoints."""

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = "Test City"
        tenant.state = "Test State"
        tenant.code = "TST"
        tenant.create_schema(sync_schema=True)

    def setUp(self):
        super().setUp()
        from django.contrib.auth import get_user_model
        from django.contrib.auth.models import Group
        from routing.models import Zone
        from crm.models import Customer
        from orders.models import Order, OrderStatus, Route, RouteStop
        from django.conf import settings
        from rest_framework.test import APIClient
        import datetime

        User = get_user_model()
        self.driver_user = User.objects.create_user(
            username="test_driver",
            email="driver@example.com",
            password="testpassword",
            is_driver=True,
            tenant_schema="test",
        )
        # Assign to Drivers group
        drivers_group, _ = Group.objects.get_or_create(name="Drivers")
        self.driver_user.groups.add(drivers_group)

        self.zone = Zone.objects.create(
            name="Test Zone", assigned_driver=self.driver_user
        )

        HAS_GIS = getattr(settings, "HAS_GDAL", False)
        if HAS_GIS:
            from django.contrib.gis.geos import Point

            loc = Point(79.0, 21.0)
        else:
            loc = {"longitude": 79.0, "latitude": 21.0}

        self.customer = Customer.objects.create(
            name="Test Customer",
            email="customer@example.com",
            zone=self.zone,
            location=loc,
            is_new=False,
        )
        # Create a pending order for today
        self.order = Order.objects.create(
            customer=self.customer,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=100.00,
        )

        # Create Route and RouteStop to authorize the driver to access this order
        self.route = Route.objects.create(
            name="Test Route",
            driver=self.driver_user,
            delivery_date=datetime.date.today(),
        )
        self.stop = RouteStop.objects.create(
            route=self.route, order=self.order, sequence_number=1
        )

        self.client = APIClient()
        self.client.force_authenticate(user=self.driver_user)

    def test_submit_undelivered_requires_pod_image(self):
        url = f"/api/erp/orders/driver/{self.order.pk}/submit-undelivered/"

        # Call without pod_image
        response = self.client.post(url, {}, HTTP_HOST="tenant.test.com")
        self.assertEqual(response.status_code, 400)
        self.assertIn("Proof of Attempt", response.data["detail"])

    def test_submit_undelivered_saves_status_and_gps(self):
        from django.core.files.uploadedfile import SimpleUploadedFile
        from orders.models import Order, OrderStatus

        url = f"/api/erp/orders/driver/{self.order.pk}/submit-undelivered/"

        # Mock image
        image_content = b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15c4\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82"
        mock_image = SimpleUploadedFile(
            "attempt.png", image_content, content_type="image/png"
        )

        data = {
            "pod_image": mock_image,
            "pod_latitude": 21.123456,
            "pod_longitude": 79.123456,
        }

        response = self.client.post(
            url, data, format="multipart", HTTP_HOST="tenant.test.com"
        )
        self.assertEqual(response.status_code, 200)

        # Verify order state in db
        self.order.refresh_from_db()
        self.assertEqual(self.order.status, OrderStatus.UNDELIVERED)
        self.assertIsNotNone(self.order.pod_image)
        self.assertEqual(float(self.order.pod_latitude), 21.123456)
        self.assertEqual(float(self.order.pod_longitude), 79.123456)


class TestDriverTripStatus(TenantTestCase):
    """Unit tests for the trip-status endpoint."""

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = "Test City"
        tenant.state = "Test State"
        tenant.code = "TST"
        tenant.create_schema(sync_schema=True)

    def setUp(self):
        super().setUp()
        from django.contrib.auth import get_user_model
        from django.contrib.auth.models import Group
        from routing.models import Zone, Driver
        from rest_framework.test import APIClient
        from crm.models import Customer
        from orders.models import Order, OrderStatus, RouteStop
        from django.conf import settings
        import datetime

        User = get_user_model()
        self.driver_user = User.objects.create_user(
            username="test_driver_status",
            email="driver_status@example.com",
            password="testpassword",
            is_driver=True,
            tenant_schema="test",
        )
        drivers_group, _ = Group.objects.get_or_create(name="Drivers")
        self.driver_user.groups.add(drivers_group)

        self.driver_profile, _ = Driver.objects.get_or_create(
            user=self.driver_user,
            defaults={
                "vehicle_plate": "TEST-5678",
                "is_available": True,
                "on_trip": False,
            },
        )
        self.driver_profile.vehicle_plate = "TEST-5678"
        self.driver_profile.is_available = True
        self.driver_profile.on_trip = False
        self.driver_profile.save()

        self.zone = Zone.objects.create(
            name="Test Status Zone", assigned_driver=self.driver_user
        )

        HAS_GIS = getattr(settings, "HAS_GDAL", False)
        if HAS_GIS:
            from django.contrib.gis.geos import Point
            loc = Point(79.0, 21.0)
        else:
            loc = {"longitude": 79.0, "latitude": 21.0}

        self.customer = Customer.objects.create(
            name="Test Status Customer",
            email="status_cust@example.com",
            zone=self.zone,
            location=loc,
            is_new=False,
        )

        self.client = APIClient()
        self.client.force_authenticate(user=self.driver_user)

    def test_trip_status_not_on_trip(self):
        url = "/api/erp/orders/driver/trip-status/"
        response = self.client.get(url, HTTP_HOST="tenant.test.com")
        self.assertEqual(response.status_code, 200)
        self.assertFalse(response.data["on_trip"])
        self.assertIsNone(response.data["active_route"])

    def test_trip_status_on_trip_no_route(self):
        self.driver_profile.on_trip = True
        self.driver_profile.save()

        url = "/api/erp/orders/driver/trip-status/"
        response = self.client.get(url, HTTP_HOST="tenant.test.com")
        self.assertEqual(response.status_code, 200)
        self.assertFalse(response.data["on_trip"])
        self.assertIsNone(response.data["active_route"])
        
        # Verify the database flag was synced back to False
        self.driver_profile.refresh_from_db()
        self.assertFalse(self.driver_profile.on_trip)

    def test_trip_status_with_active_route_not_started(self):
        from orders.models import Route, Order, OrderStatus, RouteStop
        import datetime

        order = Order.objects.create(
            customer=self.customer,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=100.00,
        )
        route = Route.objects.create(
            name="Test Route",
            driver=self.driver_user,
            delivery_date=datetime.date.today(),
        )
        RouteStop.objects.create(
            route=route,
            order=order,
            sequence_number=1,
        )

        url = "/api/erp/orders/driver/trip-status/"
        response = self.client.get(url, HTTP_HOST="tenant.test.com")
        self.assertEqual(response.status_code, 200)
        self.assertFalse(response.data["on_trip"])
        self.assertIsNotNone(response.data["active_route"])
        self.assertEqual(response.data["active_route"]["id"], str(route.id))
        self.assertFalse(response.data["active_route"]["is_started"])

    def test_trip_status_with_active_route_started(self):
        from orders.models import Route, Order, OrderStatus, RouteStop
        from django.utils import timezone
        import datetime

        order = Order.objects.create(
            customer=self.customer,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=100.00,
        )
        route = Route.objects.create(
            name="Test Route",
            driver=self.driver_user,
            delivery_date=datetime.date.today(),
            started_at=timezone.now(),
        )
        RouteStop.objects.create(
            route=route,
            order=order,
            sequence_number=1,
        )

        url = "/api/erp/orders/driver/trip-status/"
        response = self.client.get(url, HTTP_HOST="tenant.test.com")
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.data["on_trip"])
        self.assertIsNotNone(response.data["active_route"])
        self.assertTrue(response.data["active_route"]["is_started"])

    def test_today_summary_success(self):
        from orders.models import Route, Order, OrderStatus, RouteStop
        import datetime

        order = Order.objects.create(
            customer=self.customer,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=100.00,
        )
        route = Route.objects.create(
            name="Test Route",
            driver=self.driver_user,
            delivery_date=datetime.date.today(),
        )
        RouteStop.objects.create(
            route=route,
            order=order,
            sequence_number=1,
        )

        urls = [
            "/api/erp/orders/driver/today-summary/",
            "/api/erp/orders/driver/today_summary/",
            "/api/drivers/today-summary/",
            "/api/drivers/today_summary/",
            "/api/orders/driver/today-summary/",
            "/api/orders/driver/today_summary/",
        ]
        for url in urls:
            response = self.client.get(url, HTTP_HOST="tenant.test.com")
            self.assertEqual(response.status_code, 200, f"URL {url} failed with status {response.status_code}")
            self.assertTrue(response.data["has_route"])
            self.assertEqual(response.data["total_orders"], 1)



class TestDriverRouteAutoRefresh(TenantTestCase):
    """Unit tests for driver route auto-refresh when new orders come."""

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = "Test City"
        tenant.state = "Test State"
        tenant.code = "TST"
        tenant.create_schema(sync_schema=True)

    def setUp(self):
        super().setUp()
        from django.contrib.auth import get_user_model
        from django.contrib.auth.models import Group
        from routing.models import Zone, Driver
        from rest_framework.test import APIClient
        from orders.models import Route, Order, OrderStatus, RouteStop
        from django.conf import settings
        import datetime

        User = get_user_model()
        self.driver_user = User.objects.create_user(
            username="test_driver_refresh",
            email="driver_refresh@example.com",
            password="testpassword",
            is_driver=True,
            tenant_schema="test",
        )
        drivers_group, _ = Group.objects.get_or_create(name="Drivers")
        self.driver_user.groups.add(drivers_group)

        self.driver_profile, _ = Driver.objects.get_or_create(
            user=self.driver_user,
            defaults={
                "vehicle_plate": "TEST-1234",
                "is_available": True,
                "on_trip": False,
            },
        )

        self.zone = Zone.objects.create(
            name="North Zone", assigned_driver=self.driver_user
        )

        HAS_GIS = getattr(settings, "HAS_GDAL", False)
        if HAS_GIS:
            from django.contrib.gis.geos import Point
            loc = Point(79.0, 21.0)
            loc2 = Point(79.01, 21.01)
        else:
            loc = {"longitude": 79.0, "latitude": 21.0}
            loc2 = {"longitude": 79.01, "latitude": 21.01}

        from crm.models import Customer
        self.customer = Customer.objects.create(
            name="Test Customer 1",
            email="cust1@example.com",
            zone=self.zone,
            location=loc,
            is_new=False,
        )
        self.customer2 = Customer.objects.create(
            name="Test Customer 2",
            email="cust2@example.com",
            zone=self.zone,
            location=loc2,
            is_new=False,
        )

        # Create today's route with order 1
        self.order1 = Order.objects.create(
            customer=self.customer,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=50.00,
        )
        self.route = Route.objects.create(
            name="Test Driver Refresh Route",
            driver=self.driver_user,
            delivery_date=datetime.date.today(),
        )
        self.stop1 = RouteStop.objects.create(
            route=self.route, order=self.order1, sequence_number=1
        )

        # Force OSRM mocks to prevent real API requests
        self.client = APIClient()
        self.client.force_authenticate(user=self.driver_user)

    @patch("orders.services.optimizer.get_osrm_distance_matrix")
    @patch("orders.services.optimizer.get_osrm_route_geometry")
    def test_my_route_auto_refreshes_before_lock(self, mock_geom, mock_matrix):
        from orders.models import Order, OrderStatus
        import datetime

        mock_matrix.return_value = [
            [0, 100, 200],
            [100, 0, 150],
            [200, 150, 0]
        ]
        mock_geom.return_value = None

        # Initially 1 stop
        self.assertEqual(self.route.stops.count(), 1)

        # A new order comes for customer2 (in the same driver's zone)
        new_order = Order.objects.create(
            customer=self.customer2,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=75.00,
        )

        # Call my-route
        url = "/api/drivers/my-route/"
        response = self.client.get(url, HTTP_HOST="tenant.test.com")
        self.assertEqual(response.status_code, 200)

        # Check response has 2 stops now
        self.assertEqual(len(response.data["stops"]), 2)
        
        # Verify route in database has 2 stops
        self.assertEqual(self.route.stops.count(), 2)

    @patch("orders.services.optimizer.get_osrm_distance_matrix")
    @patch("orders.services.optimizer.get_osrm_route_geometry")
    def test_my_route_does_not_refresh_after_lock(self, mock_geom, mock_matrix):
        from orders.models import Order, OrderStatus
        import datetime

        mock_matrix.return_value = [
            [0, 100, 200],
            [100, 0, 150],
            [200, 150, 0]
        ]
        mock_geom.return_value = None

        # Lock the route
        self.route.is_locked = True
        self.route.save()

        # A new order comes
        new_order = Order.objects.create(
            customer=self.customer2,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=75.00,
        )

        # Call my-route
        url = "/api/drivers/my-route/"
        response = self.client.get(url, HTTP_HOST="tenant.test.com")
        self.assertEqual(response.status_code, 200)

        # Check response still has only 1 stop
        self.assertEqual(len(response.data["stops"]), 1)
        self.assertEqual(self.route.stops.count(), 1)


class TestZoneGenerationFromExcel(TenantTestCase):
    """End-to-end tests for POST /api/ems/zones/generate-from-excel/."""

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = "Test City"
        tenant.state = "Test State"
        tenant.code = "TST"
        tenant.create_schema(sync_schema=True)

    def setUp(self):
        super().setUp()
        from django.contrib.auth import get_user_model
        from django.contrib.auth.models import Group
        from routing.models import Driver
        from rest_framework.test import APIClient

        User = get_user_model()

        self.admin_user = User.objects.create_user(
            username="zone_admin",
            email="zone_admin@example.com",
            password="testpassword",
            tenant_schema="test",
        )
        erp_admins_group, _ = Group.objects.get_or_create(name="ERP_Admins")
        self.admin_user.groups.add(erp_admins_group)

        self.driver_user_a = User.objects.create_user(
            username="driver_a",
            email="driver_a@example.com",
            phone="9990000001",
            first_name="Driver",
            last_name="A",
            is_driver=True,
            tenant_schema="test",
        )
        self.driver_user_b = User.objects.create_user(
            username="driver_b",
            email="driver_b@example.com",
            phone="9990000002",
            first_name="Driver",
            last_name="B",
            is_driver=True,
            tenant_schema="test",
        )
        self.driver_a, _ = Driver.objects.get_or_create(
            user=self.driver_user_a, defaults={"vehicle_plate": "A-1"}
        )
        self.driver_b, _ = Driver.objects.get_or_create(
            user=self.driver_user_b, defaults={"vehicle_plate": "B-1"}
        )

        self.client = APIClient()
        self.client.force_authenticate(user=self.admin_user)

    def _build_workbook(self, rows):
        import openpyxl
        from io import BytesIO
        from django.core.files.uploadedfile import SimpleUploadedFile

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.append(["Name", "Phone", "Latitude", "Longitude", "Driver Phone"])
        for row in rows:
            ws.append(row)
        buf = BytesIO()
        wb.save(buf)
        buf.seek(0)
        return SimpleUploadedFile(
            "customers.xlsx",
            buf.read(),
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

    def test_generates_one_non_overlapping_zone_per_driver(self):
        from routing.models import Zone
        from crm.models import Customer

        # Two well-separated clusters, one per driver.
        rows = [
            ["Cust A1", "8880000001", 21.00, 79.00, "9990000001"],
            ["Cust A2", "8880000002", 21.01, 79.01, "9990000001"],
            ["Cust A3", "8880000003", 21.02, 79.00, "9990000001"],
            ["Cust B1", "8880000004", 21.50, 79.00, "9990000002"],
            ["Cust B2", "8880000005", 21.51, 79.01, "9990000002"],
            ["Cust B3", "8880000006", 21.52, 79.00, "9990000002"],
        ]
        upload = self._build_workbook(rows)

        url = "/api/ems/zones/generate-from-excel/"
        response = self.client.post(
            url, {"file": upload}, format="multipart", HTTP_HOST="tenant.test.com"
        )

        self.assertEqual(response.status_code, 200, response.data)
        self.assertEqual(response.data["customers_created"], 6)
        self.assertEqual(response.data["zones_created"], 2)
        self.assertEqual(response.data["drivers_matched"], 2)
        self.assertEqual(response.data["warnings"], [])

        self.driver_a.refresh_from_db()
        self.driver_b.refresh_from_db()
        self.assertIsNotNone(self.driver_a.zone_id)
        self.assertIsNotNone(self.driver_b.zone_id)
        self.assertNotEqual(self.driver_a.zone_id, self.driver_b.zone_id)

        zone_a = Zone.objects.get(assigned_driver=self.driver_user_a)
        zone_b = Zone.objects.get(assigned_driver=self.driver_user_b)
        self.assertIsNotNone(zone_a.boundary)
        self.assertIsNotNone(zone_b.boundary)

        # Zones must tile the area: no overlap between the two.
        overlap = zone_a.boundary.intersection(zone_b.boundary)
        self.assertAlmostEqual(overlap.area, 0.0, places=9)

        # Every customer should have been auto-assigned to its driver's zone
        # by the existing Zone post_save signal.
        for phone in ("8880000001", "8880000002", "8880000003"):
            self.assertEqual(Customer.objects.get(phone=phone).zone_id, zone_a.id)
        for phone in ("8880000004", "8880000005", "8880000006"):
            self.assertEqual(Customer.objects.get(phone=phone).zone_id, zone_b.id)

    def test_skips_existing_customers_without_modifying_them(self):
        from crm.models import Customer
        from django.conf import settings

        HAS_GIS = getattr(settings, "HAS_GDAL", False)
        if HAS_GIS:
            from django.contrib.gis.geos import Point

            original_loc = Point(79.00, 21.00)
        else:
            original_loc = {"lat": 21.00, "lng": 79.00}

        existing = Customer.objects.create(
            name="Original Name",
            phone="8880000001",
            address="Original Address",
            location=original_loc,
        )

        rows = [
            # Same phone as `existing`, but different name/address/coords in the sheet.
            ["Renamed In Sheet", "8880000001", 25.00, 85.00, "9990000001"],
            ["Cust A2", "8880000002", 21.01, 79.01, "9990000001"],
            ["Cust B1", "8880000004", 21.50, 79.00, "9990000002"],
        ]
        upload = self._build_workbook(rows)

        url = "/api/ems/zones/generate-from-excel/"
        response = self.client.post(
            url, {"file": upload}, format="multipart", HTTP_HOST="tenant.test.com"
        )

        self.assertEqual(response.status_code, 200, response.data)
        self.assertEqual(response.data["customers_created"], 2)
        self.assertEqual(response.data["customers_skipped_existing"], 1)

        existing.refresh_from_db()
        self.assertEqual(existing.name, "Original Name")
        self.assertEqual(existing.address, "Original Address")

        self.assertTrue(Customer.objects.filter(phone="8880000002").exists())
        self.assertTrue(Customer.objects.filter(phone="8880000004").exists())

    def test_rejects_upload_with_fewer_than_two_drivers(self):
        rows = [
            ["Cust A1", "8880000001", 21.00, 79.00, "9990000001"],
            ["Cust A2", "8880000002", 21.01, 79.01, "9990000001"],
        ]
        upload = self._build_workbook(rows)

        url = "/api/ems/zones/generate-from-excel/"
        response = self.client.post(
            url, {"file": upload}, format="multipart", HTTP_HOST="tenant.test.com"
        )

        self.assertEqual(response.status_code, 400)

    def test_rerun_updates_existing_zones_instead_of_duplicating(self):
        from routing.models import Zone

        rows = [
            ["Cust A1", "8880000001", 21.00, 79.00, "9990000001"],
            ["Cust B1", "8880000004", 21.50, 79.00, "9990000002"],
        ]
        url = "/api/ems/zones/generate-from-excel/"

        first = self.client.post(
            url, {"file": self._build_workbook(rows)}, format="multipart", HTTP_HOST="tenant.test.com"
        )
        self.assertEqual(first.status_code, 200, first.data)
        self.assertEqual(first.data["zones_created"], 2)

        second = self.client.post(
            url, {"file": self._build_workbook(rows)}, format="multipart", HTTP_HOST="tenant.test.com"
        )
        self.assertEqual(second.status_code, 200, second.data)
        self.assertEqual(second.data["zones_created"], 0)
        self.assertEqual(second.data["zones_updated"], 2)
        self.assertEqual(Zone.objects.count(), 2)
