from unittest.mock import patch, MagicMock
from django.test import TestCase


class TestTSPSolver(TestCase):
    """Unit tests for the OR-Tools TSP solver."""

    def test_solve_returns_valid_route(self):
        """Solver returns a route starting and ending at depot (index 0)."""
        from routing.services.tsp_solver import solve_tsp

        matrix = [
            [0, 10, 15, 20],
            [10, 0, 35, 25],
            [15, 35, 0, 30],
            [20, 25, 30, 0],
        ]
        with patch('routing.services.tsp_solver.TIME_LIMIT', 2):
            result = solve_tsp(matrix)

        self.assertIsNotNone(result)
        self.assertEqual(result[0], 0, 'Route must start at depot')
        self.assertEqual(result[-1], 0, 'Route must return to depot')
        self.assertEqual(len(result), 5, 'Must visit all 4 nodes + return')

    def test_solve_too_few_stops(self):
        from routing.services.tsp_solver import solve_tsp
        result = solve_tsp([[0]])
        self.assertIsNone(result)


class TestOSRMFallback(TestCase):
    """OSRM client falls back to Euclidean when the API is unavailable."""

    @patch('routing.services.osrm_client.requests.get')
    def test_fallback_on_network_error(self, mock_get):
        from routing.services.osrm_client import build_distance_matrix
        import requests as req_lib
        mock_get.side_effect = req_lib.RequestException('Connection refused')

        stops = [
            {'lat': 19.076, 'lon': 72.877},
            {'lat': 19.080, 'lon': 72.880},
            {'lat': 19.070, 'lon': 72.870},
        ]
        matrix = build_distance_matrix(stops)
        self.assertEqual(len(matrix), 3)
        self.assertEqual(len(matrix[0]), 3)
        self.assertEqual(matrix[0][0], 0.0)

    def test_raises_for_single_stop(self):
        from routing.services.osrm_client import build_distance_matrix
        with self.assertRaises(ValueError):
            build_distance_matrix([{'lat': 19.0, 'lon': 72.0}])


class TestDeductStock(TestCase):
    """Inventory service: deduct_stock_on_delivery raises on insufficient stock."""

    @patch('inventory.services.stock_service.Warehouse')
    @patch('inventory.services.stock_service.Stock')
    def test_raises_when_no_stock_record(self, MockStock, MockWarehouse):
        from inventory.services import deduct_stock_on_delivery, InsufficientStockError
        MockStock.objects.select_for_update.return_value.filter.return_value.exists.return_value = False
        MockWarehouse.objects.filter.return_value.first.return_value = MagicMock()

        item = MagicMock()
        item.product.name = 'Widget'
        item.quantity = 5
        order = MagicMock()
        order.items.select_related.return_value.all.return_value = [item]

        with self.assertRaises(InsufficientStockError):
            deduct_stock_on_delivery(order)


from django_tenants.test.cases import TenantTestCase

class TestAutoGenerateDailyRoutes(TenantTestCase):
    """Unit tests for auto_generate_daily_routes Celery task."""

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = 'Test City'
        tenant.state = 'Test State'
        tenant.code = 'TST'

    def setUp(self):
        super().setUp()
        from django.contrib.auth import get_user_model
        from routing.models import Zone
        from crm.models import Customer
        from orders.models import Order, OrderStatus
        from django.conf import settings
        import datetime

        User = get_user_model()
        self.driver_user = User.objects.create_user(
            username='test_driver',
            email='driver@example.com',
            password='testpassword',
            is_driver=True
        )
        self.zone = Zone.objects.create(
            name='Test Zone',
            assigned_driver=self.driver_user
        )

        HAS_GIS = getattr(settings, 'HAS_GDAL', False)
        if HAS_GIS:
            from django.contrib.gis.geos import Point
            loc = Point(79.0, 21.0)
        else:
            loc = {'longitude': 79.0, 'latitude': 21.0}

        self.customer = Customer.objects.create(
            name='Test Customer',
            email='customer@example.com',
            zone=self.zone,
            location=loc
        )
        # Create a pending order for today
        self.order = Order.objects.create(
            customer=self.customer,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=100.00
        )

    def test_auto_generate_daily_routes_creates_route(self):
        from routing.tasks import auto_generate_daily_routes
        from orders.models import Route, RouteStop
        import datetime

        # Run task
        results = auto_generate_daily_routes()

        # Check results
        self.assertIn('test', results)
        stats = results['test']
        self.assertEqual(stats['status'], 'success')
        self.assertEqual(stats['created_routes'], 1)
        self.assertEqual(stats['skipped_zones'], 0)

        # Verify Route was created in database
        route = Route.objects.filter(driver=self.driver_user, delivery_date=datetime.date.today()).first()
        self.assertIsNotNone(route)
        self.assertEqual(route.name, f"Test Zone - {datetime.date.today().strftime('%Y-%m-%d')}")

        # Verify RouteStop was created
        stop = RouteStop.objects.filter(route=route).first()
        self.assertIsNotNone(stop)
        self.assertEqual(stop.order, self.order)


class TestSubmitUndelivered(TenantTestCase):
    """Unit tests for submit_undelivered and mark_undelivered endpoints."""

    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = 'Test City'
        tenant.state = 'Test State'
        tenant.code = 'TST'

    def setUp(self):
        super().setUp()
        from django.contrib.auth import get_user_model
        from django.contrib.auth.models import Group
        from routing.models import Zone
        from crm.models import Customer
        from orders.models import Order, OrderStatus, Route, RouteStop
        from django.conf import settings
        from rest_framework.test import APIClient
        import datetime

        User = get_user_model()
        self.driver_user = User.objects.create_user(
            username='test_driver',
            email='driver@example.com',
            password='testpassword',
            is_driver=True,
            tenant_schema='test'
        )
        # Assign to Drivers group
        drivers_group, _ = Group.objects.get_or_create(name='Drivers')
        self.driver_user.groups.add(drivers_group)

        self.zone = Zone.objects.create(
            name='Test Zone',
            assigned_driver=self.driver_user
        )

        HAS_GIS = getattr(settings, 'HAS_GDAL', False)
        if HAS_GIS:
            from django.contrib.gis.geos import Point
            loc = Point(79.0, 21.0)
        else:
            loc = {'longitude': 79.0, 'latitude': 21.0}

        self.customer = Customer.objects.create(
            name='Test Customer',
            email='customer@example.com',
            zone=self.zone,
            location=loc
        )
        # Create a pending order for today
        self.order = Order.objects.create(
            customer=self.customer,
            scheduled_delivery_date=datetime.date.today(),
            status=OrderStatus.PENDING,
            total=100.00
        )

        # Create Route and RouteStop to authorize the driver to access this order
        self.route = Route.objects.create(
            name='Test Route',
            driver=self.driver_user,
            delivery_date=datetime.date.today()
        )
        self.stop = RouteStop.objects.create(
            route=self.route,
            order=self.order,
            sequence_number=1
        )

        self.client = APIClient()
        self.client.force_authenticate(user=self.driver_user)

    def test_submit_undelivered_requires_pod_image(self):
        url = f'/api/erp/orders/driver/{self.order.pk}/submit-undelivered/'
        
        # Call without pod_image
        response = self.client.post(url, {}, HTTP_HOST='tenant.test.com')
        self.assertEqual(response.status_code, 400)
        self.assertIn('Proof of Attempt', response.data['detail'])

    def test_submit_undelivered_saves_status_and_gps(self):
        from django.core.files.uploadedfile import SimpleUploadedFile
        from orders.models import Order, OrderStatus
        url = f'/api/erp/orders/driver/{self.order.pk}/submit-undelivered/'
        
        # Mock image
        image_content = b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15c4\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82'
        mock_image = SimpleUploadedFile("attempt.png", image_content, content_type="image/png")
        
        data = {
            'pod_image': mock_image,
            'pod_latitude': 21.123456,
            'pod_longitude': 79.123456
        }
        
        response = self.client.post(url, data, format='multipart', HTTP_HOST='tenant.test.com')
        self.assertEqual(response.status_code, 200)
        
        # Verify order state in db
        self.order.refresh_from_db()
        self.assertEqual(self.order.status, OrderStatus.UNDELIVERED)
        self.assertIsNotNone(self.order.pod_image)
        self.assertEqual(float(self.order.pod_latitude), 21.123456)
        self.assertEqual(float(self.order.pod_longitude), 79.123456)

