# Generated by Django 6.0.4 on 2026-05-15 10:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_driver_on_trip_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
