# Generated by Django 6.0.4 on 2026-05-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_driver_on_trip_zone_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profiles', to='routing.zone'),
        ),
    ]
