# Generated by Django 4.2.30 on 2026-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_driver_on_trip_driver_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='on_trip',
            field=models.BooleanField(default=False),
        ),
    ]
