# Generated by Django 4.2.30 on 2026-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_driver_on_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='is_test_route',
            field=models.BooleanField(default=False, help_text='Auto-created dummy route for GPS tracking tests.'),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='route',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
