# Generated by Django 4.2.30 on 2026-05-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_warehouse_latitude_warehouse_longitude'),
        ('routing', '0006_route_completed_at_route_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='The warehouse this route starts and ends at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='inventory.warehouse'),
        ),
    ]
