# Generated by Django 5.2.11 on 2026-05-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_rawmaterial_remove_stockmovement_product_and_more"),
        ("routing", "0007_route_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="The primary warehouse this driver is associated with.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drivers",
                to="inventory.warehouse",
            ),
        ),
    ]
