# Generated by Django 5.2.11 on 2026-05-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routing", "0008_driver_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="additional_drivers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional drivers assigned to this route in case of emergency.",
                related_name="shared_routes",
                to="routing.driver",
            ),
        ),
    ]
