# Generated by Django 5.2.15 on 2026-08-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0009_route_additional_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_secured',
            field=models.BooleanField(default=False, help_text='Indicates whether this route is secured.'),
        ),
    ]
