# Generated by Django 4.2.30 on 2026-05-06 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_qr_code_id_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
