# Generated by Django 6.0.4 on 2026-05-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_customer_qr_code_id'),
        ('routing', '0002_driver_on_trip_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='routing.zone'),
        ),
    ]
