# Generated by Django 4.2.30 on 2026-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_new',
            field=models.BooleanField(default=True, help_text='True if the customer is in trial mode / has not subscribed yet.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trial_approved',
            field=models.BooleanField(default=False, help_text='True if admin approved sending demo product / trial delivery to this new customer.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
