# Generated by Django 4.2.30 on 2026-05-05 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('alternate_day', 'Alternate Day'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('custom_days', models.JSONField(blank=True, default=list, help_text='For custom frequency: list of weekday numbers (0=Mon, 6=Sun), e.g. [0, 2, 4]')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for indefinite subscription.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused (Vacation)'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_paused', models.BooleanField(default=False)),
                ('pause_start', models.DateField(blank=True, null=True)),
                ('pause_end', models.DateField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSkipDate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_dates', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('subscription', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='inventory.product')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'product')},
            },
        ),
    ]
