# Generated by Django 4.2.30 on 2026-05-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscriptionskipdate',
            options={},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='delivery_notes',
            new_name='special_instructions',
        ),
        migrations.RenameField(
            model_name='subscriptionskipdate',
            old_name='date',
            new_name='skip_date',
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='custom_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('alternate', 'Alternate Days'), ('weekdays', 'Mon-Fri'), ('weekends', 'Sat-Sun'), ('custom', 'Custom Days')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionskipdate',
            unique_together={('subscription', 'skip_date')},
        ),
    ]
