# Generated by Django 4.2.30 on 2026-05-05 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='E.g., Maharashtra SGST 9%', max_length=200)),
                ('state', models.CharField(help_text='State this rule applies to.', max_length=100)),
                ('tax_type', models.CharField(choices=[('sgst', 'SGST (State GST)'), ('cgst', 'CGST (Central GST)'), ('igst', 'IGST (Integrated GST)'), ('exempt', 'Exempt')], max_length=10)),
                ('rate_percentage', models.DecimalField(decimal_places=2, help_text='Tax rate as a percentage, e.g. 9.00 for 9%.', max_digits=5)),
                ('tax_category', models.CharField(choices=[('standard', 'Standard'), ('essential', 'Essential'), ('exempt', 'Exempt')], default='standard', help_text='Product category this rule applies to.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
                'ordering': ['state', 'tax_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductTaxCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_category', models.CharField(choices=[('standard', 'Standard'), ('essential', 'Essential'), ('exempt', 'Exempt')], default='standard', max_length=20)),
                ('hsn_code', models.CharField(blank=True, help_text='Harmonized System Nomenclature code for GST.', max_length=8)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_category_info', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Tax Category',
                'verbose_name_plural': 'Product Tax Categories',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTaxBreakdown',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_type', models.CharField(choices=[('sgst', 'SGST (State GST)'), ('cgst', 'CGST (Central GST)'), ('igst', 'IGST (Integrated GST)'), ('exempt', 'Exempt')], max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_breakdowns', to='finance.invoice')),
                ('tax_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_breakdowns', to='taxation.taxrule')),
            ],
            options={
                'ordering': ['tax_type'],
            },
        ),
    ]
