# Generated by Django 4.2.30 on 2026-05-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttaxcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taxrule',
            options={'ordering': ['state', 'tax_type']},
        ),
        migrations.AlterField(
            model_name='producttaxcategory',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='tax_category',
            field=models.CharField(choices=[('standard', 'Standard'), ('essential', 'Essential'), ('exempt', 'Exempt')], default='standard', max_length=20),
        ),
        migrations.DeleteModel(
            name='InvoiceTaxBreakdown',
        ),
    ]
