# Generated by Django 4.2.30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_driver_on_trip'),
        ('tracking', '0002_drivertrail_cleaned_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrail',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trails', to='routing.route'),
        ),
    ]
