# Generated by Django 4.2.30 on 2026-05-05 09:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_route_alter_orderitem_options_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
