# Generated by Django 6.0.4 on 2026-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_route_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pod_image',
            field=models.ImageField(blank=True, null=True, upload_to='pod_images/'),
        ),
        migrations.AddField(
            model_name='route',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
