# Generated by Django 6.0.4 on 2026-05-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_route_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pod_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pod_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
