# Generated by Django 5.2.11 on 2026-05-24 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_route_is_locked_route_status_deliverylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="additional_drivers",
            field=models.ManyToManyField(
                blank=True,
                related_name="additional_routes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
