# Generated by Django 4.2.30 on 2026-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_route_additional_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_special',
            field=models.BooleanField(default=False, help_text='True if this is a one-time special/extra order placed outside of any subscription.'),
        ),
    ]
