# Generated by Django 4.2.30 on 2026-06-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_is_special_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('on_account', 'On Account (Monthly Bill)')], default='on_account', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, help_text='UPI Transaction Ref / UTR', max_length=100),
        ),
    ]
