# Generated by Django 4.2.30 on 2026-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_amount_collected_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arriving_notification_sent',
            field=models.BooleanField(default=False, help_text="True if 'arriving shortly' proximity notification has been sent to the customer."),
        ),
    ]
