# Generated by Django 4.2.30 on 2026-06-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_arriving_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='actual_distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='route',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='stoppage_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
