# Generated by Django 4.2.30 on 2026-06-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_route_actual_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stoppage_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
